module.exports = `
    input BookingInput {
        created_by: ID!,
        associated_users: [ID],
        from: String,
        to: String
    }

    type Booking {
        created_by: ID!,
        associated_users: [ID],
        from: String,
        to: String
    }
`