module.exports = `
  # QUERY  
  type RootQuery {
    refreshToken(refreshToken: String): String
    login(email: String! password: String!): AuthData!

    checkUsernames(username: String): String
    checkEmails(email: String): String

    user(username: String): User
    userById(ID: ID!): User
    me: User

    bookings: [Booking]
    bookingsByDate(date: String): [Booking]

    rooms: [Room]

    subscripitonModels: [Subscription]
  }

  # MUTATION  
  type RootMutation {
    createUser(userInput: UserInput): User
    deactivateUser: String
    deleteUser: String

    createBooking(bookingInput: BookingInput): String
    removeBooking(booking_id: String): String

    addCredits(amount: Float): String

    changeSubscription(subscription_id: ID): User
  }

  schema {
    query: RootQuery
    mutation: RootMutation
  }
`